version: '2.1'

services:
  vue-cosmosdb:
    image: vue-cosmosdb
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3003:3003
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 index.js